apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 3
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: container
          image: tessssssssy/campingontopfrontend:8.VERSION
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 5